### ISSUE TITLE
Could not deploy on Bluemix Buildpack problems with node-zopfli@2.0.2

### ISSUE THREAD

**Issue by rmey** [IBM-Bluemix/insurance-bot-dashboard#40]
There seems to be a problem with gyp and the buildpack used on bleumix please check this log.
API/10Updated app with guid 95eec182-64c2-47b9-afd8-fdc7c05bc993 ({"state"=>"STARTED"})Jan 8, 2017 11:06:37 AM
STG/0Downloading java_buildpack...Jan 8, 2017 11:06:37 AM
STG/0Downloading ruby_buildpack...Jan 8, 2017 11:06:37 AM
STG/0Downloading swift_buildpack_v2_0_2-20161118-1326...Jan 8, 2017 11:06:37 AM
STG/0Downloading nodejs_buildpack...Jan 8, 2017 11:06:37 AM
STG/0Downloading go_buildpack...Jan 8, 2017 11:06:37 AM
STG/0Downloaded ruby_buildpackJan 8, 2017 11:06:37 AM
STG/0Downloaded go_buildpackJan 8, 2017 11:06:37 AM
STG/0Downloading xpages_buildpack...Jan 8, 2017 11:06:37 AM
STG/0Downloaded nodejs_buildpackJan 8, 2017 11:06:37 AM
STG/0Downloading php_buildpack...Jan 8, 2017 11:06:37 AM
STG/0Downloaded java_buildpackJan 8, 2017 11:06:37 AM
STG/0Downloading staticfile_buildpack...Jan 8, 2017 11:06:37 AM
STG/0Downloading binary_buildpack...Jan 8, 2017 11:06:37 AM
STG/0Downloaded swift_buildpack_v2_0_2-20161118-1326Jan 8, 2017 11:06:37 AM
STG/0Downloading liberty-for-java_v3_4_1-20161030-2241...Jan 8, 2017 11:06:37 AM
STG/0Downloaded xpages_buildpackJan 8, 2017 11:06:37 AM
STG/0Downloading sdk-for-nodejs_v3_8-20161006-1211...Jan 8, 2017 11:06:37 AM
STG/0Downloaded python_buildpackJan 8, 2017 11:06:37 AM
STG/0Downloading liberty-for-java_v3_5-20161114-1152...Jan 8, 2017 11:06:37 AM
STG/0Downloaded binary_buildpackJan 8, 2017 11:06:37 AM
STG/0Downloaded staticfile_buildpackJan 8, 2017 11:06:37 AM
STG/0Downloaded php_buildpackJan 8, 2017 11:06:37 AM
STG/0Downloading dotnet-core_v1_0_1-20161005-1225...Jan 8, 2017 11:06:37 AM
STG/0Downloading xpages_buildpack_v1_2_1-20160913-103...Jan 8, 2017 11:06:37 AM
STG/0Downloaded liberty-for-java_v3_4_1-20161030-2241Jan 8, 2017 11:06:37 AM
STG/0Downloading sdk-for-nodejs...Jan 8, 2017 11:06:37 AM
STG/0Downloaded sdk-for-nodejs_v3_8-20161006-1211Jan 8, 2017 11:06:37 AM
STG/0Downloaded liberty-for-java_v3_5-20161114-1152Jan 8, 2017 11:06:37 AM
STG/0Downloading swift_buildpack...Jan 8, 2017 11:06:37 AM
STG/0Downloaded xpages_buildpack_v1_2_1-20160913-103Jan 8, 2017 11:06:37 AM
STG/0Downloaded dotnet-core_v1_0_1-20161005-1225Jan 8, 2017 11:06:37 AM
STG/0Downloading dotnet-core...Jan 8, 2017 11:06:37 AM
STG/0Downloading noop-buildpack...Jan 8, 2017 11:06:37 AM
STG/0Downloaded liberty-for-javaJan 8, 2017 11:06:37 AM
STG/0Downloaded sdk-for-nodejsJan 8, 2017 11:06:37 AM
STG/0Downloaded dotnet-coreJan 8, 2017 11:06:37 AM
STG/0Creating containerJan 8, 2017 11:06:37 AM
STG/0Downloaded noop-buildpackJan 8, 2017 11:06:37 AM
STG/0Successfully created containerJan 8, 2017 11:06:45 AM
STG/0Downloading app package...Jan 8, 2017 11:06:45 AM
STG/0Staging...Jan 8, 2017 11:06:46 AM
STG/0Downloaded app package (835K)Jan 8, 2017 11:06:46 AM
STG/0-----> IBM SDK for Node.js Buildpack v3.9-20161128-1327Jan 8, 2017 11:06:47 AM
STG/0 Based on Cloud Foundry Node.js Buildpack v1.5.20Jan 8, 2017 11:06:47 AM
STG/0-----> Creating runtime environmentJan 8, 2017 11:06:47 AM
STG/0Jan 8, 2017 11:06:47 AM
STG/0 NPM_CONFIG_LOGLEVEL=errorJan 8, 2017 11:06:47 AM
STG/0 NODE_MODULES_CACHE=trueJan 8, 2017 11:06:47 AM
STG/0-----> Installing binariesJan 8, 2017 11:06:47 AM
STG/0 NPM_CONFIG_PRODUCTION=trueJan 8, 2017 11:06:47 AM
STG/0 Resolving node version >=4.2.0 via 'node-version-resolver'Jan 8, 2017 11:06:47 AM
STG/0 engines.npm (package.json): ^3.0.0Jan 8, 2017 11:06:47 AM
STG/0 Installing IBM SDK for Node.js (4.6.2) from cacheJan 8, 2017 11:06:47 AM
STG/0 Resolving npm version ^3.0.0 via semver.io...Jan 8, 2017 11:06:48 AM
STG/0 Downloading and installing npm 3.10.10 (replacing version 2.15.11)...Jan 8, 2017 11:06:49 AM
STG/0-----> Restoring cacheJan 8, 2017 11:06:59 AM
STG/0 Skipping cache restore (new runtime signature)Jan 8, 2017 11:06:59 AM
STG/0-----> Checking and configuring service extensions before installing dependenciesJan 8, 2017 11:06:59 AM
STG/0-----> Building dependenciesJan 8, 2017 11:07:00 AM
STG/0 Installing node modules (package.json)Jan 8, 2017 11:07:00 AM
STG/0 > node-zopfli@2.0.2 install /tmp/app/node_modules/node-zopfliJan 8, 2017 11:08:14 AM
STG/0Jan 8, 2017 11:08:14 AM
STG/0Jan 8, 2017 11:08:14 AM
STG/0 > node-pre-gyp install --fallback-to-buildJan 8, 2017 11:08:14 AM
STG/0 node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@2.0.2 and node@4.6.2 (node-v46 ABI) (falling back to source compile with node-gyp)Jan 8, 2017 11:08:16 AM
STG/0 node-pre-gyp ERR! Tried to download(403): https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.2-node-v46-linux-x64.tar.gzJan 8, 2017 11:08:16 AM
STG/0 gyp ERR! configure errorJan 8, 2017 11:08:17 AM
STG/0 gyp ERR! stack Error: `gyp` failed with exit code: nullJan 8, 2017 11:08:17 AM
STG/0 gyp ERR! stack at emitTwo (events.js:87:13)Jan 8, 2017 11:08:17 AM
STG/0 gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)Jan 8, 2017 11:08:17 AM
STG/0 gyp ERR! System Linux 3.19.0-33-genericJan 8, 2017 11:08:17 AM
STG/0 gyp ERR! command "/tmp/app/vendor/node/bin/node" "/tmp/app/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/tmp/app/node_modules/node-zopfli/lib/binding/node-v46-linux-x64/zopfli.node" "--module_name=zopfli" "--module_path=/tmp/app/node_modules/node-zopfli/lib/binding/node-v46-linux-x64"Jan 8, 2017 11:08:17 AM
STG/0 gyp ERR! node -v v4.6.2Jan 8, 2017 11:08:17 AM
STG/0 gyp ERR! cwd /tmp/app/node_modules/node-zopfliJan 8, 2017 11:08:17 AM
STG/0 gyp ERR! node-gyp -v v3.4.0Jan 8, 2017 11:08:17 AM
STG/0 gyp ERR! not okJan 8, 2017 11:08:17 AM
STG/0 node-pre-gyp ERR! build errorJan 8, 2017 11:08:17 AM
STG/0 node-pre-gyp ERR! stack Error: Failed to execute '/tmp/app/vendor/node/bin/node /tmp/app/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/tmp/app/node_modules/node-zopfli/lib/binding/node-v46-linux-x64/zopfli.node --module_name=zopfli --module_path=/tmp/app/node_modules/node-zopfli/lib/binding/node-v46-linux-x64' (1)Jan 8, 2017 11:08:17 AM
STG/0 node-pre-gyp ERR! stack at ChildProcess.emit (events.js:172:7)Jan 8, 2017 11:08:17 AM
STG/0 node-pre-gyp ERR! stack at ChildProcess.<anonymous> (/tmp/app/node_modules/node-pre-gyp/lib/util/compile.js:83:29)Jan 8, 2017 11:08:17 AM
STG/0 node-pre-gyp ERR! stack at emitTwo (events.js:87:13)Jan 8, 2017 11:08:17 AM
STG/0 node-pre-gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)Jan 8, 2017 11:08:17 AM
STG/0 node-pre-gyp ERR! stack at maybeClose (internal/child_process.js:854:16)Jan 8, 2017 11:08:17 AM
STG/0 node-pre-gyp ERR! command "/tmp/app/vendor/node/bin/node" "/tmp/app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"Jan 8, 2017 11:08:17 AM
STG/0 node-pre-gyp ERR! node -v v4.6.2Jan 8, 2017 11:08:17 AM
STG/0 node-pre-gyp ERR! not okJan 8, 2017 11:08:17 AM
STG/0 node-pre-gyp ERR! cwd /tmp/app/node_modules/node-zopfliJan 8, 2017 11:08:17 AM
STG/0 Failed to execute '/tmp/app/vendor/node/bin/node /tmp/app/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/tmp/app/node_modules/node-zopfli/lib/binding/node-v46-linux-x64/zopfli.node --module_name=zopfli --module_path=/tmp/app/node_modules/node-zopfli/lib/binding/node-v46-linux-x64' (1)Jan 8, 2017 11:08:17 AM
STG/0-----> Build failedJan 8, 2017 11:08:17 AM
STG/0/tmp/buildpacks/a44d7b5afe22d91147f8e49a730b9f3a/lib/dependencies.sh: line 1: 258 Killed npm install --unsafe-perm --userconfig $build_dir/.npmrc 2>&1Jan 8, 2017 11:08:17 AM
STG/0Jan 8, 2017 11:08:18 AM
STG/0 - Dangerous semver range (>) in engines.nodeJan 8, 2017 11:08:18 AM
STG/0Jan 8, 2017 11:08:18 AM
STG/0 Some possible problems:Jan 8, 2017 11:08:18 AM
STG/0Failed to compile dropletJan 8, 2017 11:08:18 AM
STG/0 http://docs.cloudfoundry.org/buildpacks/node/node-tips.htmlJan 8, 2017 11:08:18 AM
STG/0Staging failed: Exited with status 223 (out of memory)Jan 8, 2017 11:08:18 AM
STG/0Destroying containerJan 8, 2017 11:08:18 AM
API/5Failed to stage application: staging failedJan 8, 2017 11:08:18 AM
STG/0Successfully destroyed containerJan 8, 2017 11:08:20 AM
API/6Updated app with guid 95eec182-64c2-47b9-afd8-fdc7c05bc993 ({"name"=>"insurance-toolchain-rm2017-dashboard-OLD-1483870649"})Jan 8, 2017 11:16:15 AM
API/1Updated app with guid 95eec182-64c2-47b9-afd8-fdc7c05bc993 ({"name"=>"insurance-toolchain-rm2017-dashboard"})

**Comment by rmey** [comment]
You should fix the package.json with correct and matching values for npm and node version. I fixed the issue for now with "node": "4.2.4". See also https://nodejs.org/en/download/releases/ for a list of node versions and their belonging npm versions.

**Comment by l2fprod** [comment]
The *Exited with status 223 (out of memory)* might be the real issue. But indeed with a different version of node like 4.2.4 or 6.7.0 it works. Going to bump the node version anyway.
